/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Community;
import io.swagger.model.Content;
import io.swagger.model.InlineResponse403;
import io.swagger.model.InlineResponse404;
import io.swagger.model.Person;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-07-24T19:39:37.078-07:00")

@Api(value = "community", description = "the community API")
public interface CommunityApi {

    @ApiOperation(value = "add community member", notes = "It seems this should be a Community admin function. Perhaps it would be better for a Person to Join a Community, or optionally Leave a Community. Adding / removing members needs more though. It's possible that members may need to be invited or allowed to join base on some criteria (group vote, etc.)", response = Void.class, tags={ "Community", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Void.class),
        @ApiResponse(code = 401, message = "", response = Object.class),
        @ApiResponse(code = 403, message = "", response = InlineResponse403.class),
        @ApiResponse(code = 404, message = "", response = InlineResponse404.class),
        @ApiResponse(code = 409, message = "", response = Object.class),
        @ApiResponse(code = 422, message = "", response = Object.class),
        @ApiResponse(code = 500, message = "", response = Object.class) })
    
    @RequestMapping(value = "/community/{community_uuid}/members/{person_uuid}",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> addCommunityMember(@ApiParam(value = "",required=true ) @PathVariable("community_uuid") String community_uuid,@ApiParam(value = "",required=true ) @PathVariable("person_uuid") String person_uuid);


    @ApiOperation(value = "create a Community", notes = "", response = Community.class, tags={ "Community", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "", response = Community.class),
        @ApiResponse(code = 401, message = "", response = Object.class),
        @ApiResponse(code = 403, message = "", response = InlineResponse403.class),
        @ApiResponse(code = 404, message = "", response = InlineResponse404.class),
        @ApiResponse(code = 409, message = "", response = Object.class),
        @ApiResponse(code = 422, message = "", response = Object.class),
        @ApiResponse(code = 500, message = "", response = Object.class) })
    
    @RequestMapping(value = "/community",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Community> createCommunity(@ApiParam(value = ""  )  @Valid @RequestBody Community body);


    @ApiOperation(value = "get communities by query parameters", notes = "", response = Community.class, responseContainer = "List", tags={ "Community", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Community.class, responseContainer = "List") })
    
    @RequestMapping(value = "/community",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Community>> getCommunitiesByQueryParameters(@ApiParam(value = "") @RequestParam(value = "name", required = false) String name,@ApiParam(value = "") @RequestParam(value = "enspath", required = false) String enspath,@ApiParam(value = "") @RequestParam(value = "parentid", required = false) String parentid,@ApiParam(value = "") @RequestParam(value = "organizationid", required = false) String organizationid);


    @ApiOperation(value = "get community", notes = "", response = Community.class, tags={ "Community", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Community.class) })
    
    @RequestMapping(value = "/community/{uuid}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Community> getCommunity(@ApiParam(value = "",required=true ) @PathVariable("uuid") String uuid);


    @ApiOperation(value = "get community content", notes = "", response = Content.class, responseContainer = "List", tags={ "Community", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Content.class, responseContainer = "List") })
    
    @RequestMapping(value = "/community/{uuid}/content",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Content>> getCommunityContent(@ApiParam(value = "",required=true ) @PathVariable("uuid") String uuid);


    @ApiOperation(value = "get community members", notes = "", response = Person.class, responseContainer = "List", tags={ "Community", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Person.class, responseContainer = "List") })
    
    @RequestMapping(value = "/community/{uuid}/members",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Person>> getCommunityMembers(@ApiParam(value = "",required=true ) @PathVariable("uuid") String uuid);


    @ApiOperation(value = "get community sub communities", notes = "", response = Community.class, responseContainer = "List", tags={ "Community", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Community.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "", response = Object.class),
        @ApiResponse(code = 403, message = "", response = InlineResponse403.class),
        @ApiResponse(code = 404, message = "", response = InlineResponse404.class),
        @ApiResponse(code = 409, message = "", response = Object.class),
        @ApiResponse(code = 422, message = "", response = Object.class),
        @ApiResponse(code = 500, message = "", response = Object.class) })
    
    @RequestMapping(value = "/community/{uuid}/community",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Community>> getCommunitySubCommunities(@ApiParam(value = "",required=true ) @PathVariable("uuid") String uuid);


    @ApiOperation(value = "update a community", notes = "", response = Void.class, tags={ "Community", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Void.class),
        @ApiResponse(code = 401, message = "", response = Object.class),
        @ApiResponse(code = 403, message = "", response = InlineResponse403.class),
        @ApiResponse(code = 404, message = "", response = InlineResponse404.class),
        @ApiResponse(code = 409, message = "", response = Object.class),
        @ApiResponse(code = 422, message = "", response = Object.class),
        @ApiResponse(code = 500, message = "", response = Object.class) })
    
    @RequestMapping(value = "/community",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateCommunity(@ApiParam(value = ""  )  @Valid @RequestBody Community body);

}
