/**
 * VerityReputation
 * This is a simple Verity reputation API. You can find out more about Verity at <a href='http://getcrystal.net'>http://getcrystal.net</a>  For this sample, you can use the api key 'special-key' for tests that need authorization (authorization filters).  Where possible we specify multi-hashes as unique identifiers that can be used by distributed cryptographically secure systems (blockchains) Where possible we specify hyper-media links (e.g. JSON-LD) to describe data that is linked in graph structures by nature (blockchain data, IPFS data, etc.)  Agents, Entity and Activity should map to provenance ontology described in https://www.w3.org/TR/prov-o Transaction is an implementation that maps to TrustAtoms. https://github.com/CoMakery/trust-exchange/blob/master/README.md This is a simple Verity reputation API. You can find out more about Verity at <a href='http://getcrystal.net'>http://getcrystal.net</a>  For this sample, you can use the api key 'special-key' for tests that need authorization (authorization filters).  Where possible we specify multi-hashes as unique identifiers that can be used by distributed cryptographically secure systems (blockchains) Where possible we specify hyper-media links (e.g. JSON-LD) to describe data that is linked in graph structures by nature (blockchain data, IPFS data, etc.)  Agents, Entity and Activity should map to provenance ontology described in https://www.w3.org/TR/prov-o Transaction is an implementation that maps to TrustAtoms. https://github.com/CoMakery/trust-exchange/blob/master/README.md
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package site.verity.client.mode;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * A fundamental unit of reputation value transfer, attestation or claim. Represents a singular event that transfers or bestows reputation to the target/recipient. The sender/source can be a person, software agent, organization or the like. Intended to be independent of database or blockchain so all IDs should be globally identifiable hashes in multi-hash format pointing to the canonical representation or permanent public store.  Similar to and should map to TrustAtom https://github.com/CoMakery/trust-exchange/blob/master/README.md
 */
@ApiModel(description = "A fundamental unit of reputation value transfer, attestation or claim. Represents a singular event that transfers or bestows reputation to the target/recipient. The sender/source can be a person, software agent, organization or the like. Intended to be independent of database or blockchain so all IDs should be globally identifiable hashes in multi-hash format pointing to the canonical representation or permanent public store.  Similar to and should map to TrustAtom https://github.com/CoMakery/trust-exchange/blob/master/README.md")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-25T09:44:21.918-08:00")
public class Transaction   {
  @SerializedName("uuid")
  private String uuid = null;

  @SerializedName("valueActionId")
  private String valueActionId = null;

  @SerializedName("sourceAgentId")
  private String sourceAgentId = null;

  @SerializedName("targetAgentId")
  private String targetAgentId = null;

  @SerializedName("timeStamp")
  private DateTime timeStamp = null;

  @SerializedName("value")
  private Integer value = null;

  public Transaction uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * UUID, GUID, HASH,  MultiHash or ProxyContract Address that represents this object
   * @return uuid
  **/
  @ApiModelProperty(example = "null", required = true, value = "UUID, GUID, HASH,  MultiHash or ProxyContract Address that represents this object")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public Transaction valueActionId(String valueActionId) {
    this.valueActionId = valueActionId;
    return this;
  }

   /**
   * link that describes the way this score was derived, or the community feature that affects the way the value will be interpreted. Could be a link or content addressable graph pointing to a richer source of description or information.
   * @return valueActionId
  **/
  @ApiModelProperty(example = "null", required = true, value = "link that describes the way this score was derived, or the community feature that affects the way the value will be interpreted. Could be a link or content addressable graph pointing to a richer source of description or information.")
  public String getValueActionId() {
    return valueActionId;
  }

  public void setValueActionId(String valueActionId) {
    this.valueActionId = valueActionId;
  }

  public Transaction sourceAgentId(String sourceAgentId) {
    this.sourceAgentId = sourceAgentId;
    return this;
  }

   /**
   * Get sourceAgentId
   * @return sourceAgentId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getSourceAgentId() {
    return sourceAgentId;
  }

  public void setSourceAgentId(String sourceAgentId) {
    this.sourceAgentId = sourceAgentId;
  }

  public Transaction targetAgentId(String targetAgentId) {
    this.targetAgentId = targetAgentId;
    return this;
  }

   /**
   * Get targetAgentId
   * @return targetAgentId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getTargetAgentId() {
    return targetAgentId;
  }

  public void setTargetAgentId(String targetAgentId) {
    this.targetAgentId = targetAgentId;
  }

  public Transaction timeStamp(DateTime timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * timestamp or block height of blockchain at time of creation. Should be self-describing as to format and meaning.
   * @return timeStamp
  **/
  @ApiModelProperty(example = "null", value = "timestamp or block height of blockchain at time of creation. Should be self-describing as to format and meaning.")
  public DateTime getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(DateTime timeStamp) {
    this.timeStamp = timeStamp;
  }

  public Transaction value(Integer value) {
    this.value = value;
    return this;
  }

   /**
   * value (points) awarded at the time of the transaction. Immutable. Use ValueActionId to lookup the 'current' value if you want to calculate points based on the latest value as apposed to the value at time transaction was created. This allows for 'retroactive' adjustment of points.
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "value (points) awarded at the time of the transaction. Immutable. Use ValueActionId to lookup the 'current' value if you want to calculate points based on the latest value as apposed to the value at time transaction was created. This allows for 'retroactive' adjustment of points.")
  public Integer getValue() {
    return value;
  }

  public void setValue(Integer value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.uuid, transaction.uuid) &&
        Objects.equals(this.valueActionId, transaction.valueActionId) &&
        Objects.equals(this.sourceAgentId, transaction.sourceAgentId) &&
        Objects.equals(this.targetAgentId, transaction.targetAgentId) &&
        Objects.equals(this.timeStamp, transaction.timeStamp) &&
        Objects.equals(this.value, transaction.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, valueActionId, sourceAgentId, targetAgentId, timeStamp, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    valueActionId: ").append(toIndentedString(valueActionId)).append("\n");
    sb.append("    sourceAgentId: ").append(toIndentedString(sourceAgentId)).append("\n");
    sb.append("    targetAgentId: ").append(toIndentedString(targetAgentId)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

